name: star_realms_health_counter
description: Star Realms Health Counter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  intl: ^0.19.0
  riverpod_annotation: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
